spring:
  datasource:
    url: jdbc:h2:mem:ordersdb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Consola H2
spring.h2.console.enabled: true
spring.h2.console.path: /h2-console

# Actuator más abierto solo en dev
management.endpoints.web.exposure.include: "*"

# Seguridad dev (permitimos h2-console)
security:
  dev: true
