spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:orders}
    username: ${DB_USER:orders}
    password: ${DB_PASS:secret}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.lob.non_contextual_creation: true

server:
  port: ${SERVER_PORT:8080}

# CORS configurable por env
app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:https://mi-frontend.com}
  orders:
    max-items: ${MAX_ITEMS:100}
